#!/usr/bin/env bash
#
# get_all_pantheon_domains
#
# Create a list that maps site domain names to Pantheon site names.  For example,
#     its.umich.edu,its-its-umich-drupal7
#     sites.its.umich.edu,its-its-umich-drupal7
#     www.its.umich.edu,its-its-umich-drupal7
#
# Usage:
#     export PANTHEON_ORG="regenets-of-the-university-of-michigan"
#     ./get_all_pantheon_domains

PANTHEON_ORG="${PANTHEON_ORG:-regents-of-the-university-of-michigan}"
PARALLELISM=16

OUTFILE="pantheon-domains-$(date +%Y%m%d).txt"

if [ -d './tmp' ] ; then
    SCRATCHDIR="$(pwd)/tmp"
else
    SCRATCHDIR="/tmp"
fi

SITES=$(mktemp "${SCRATCHDIR}/pantheon-domains.sites.XXXXXXXX")
LOG=$(mktemp "${SCRATCHDIR}/pantheon-domains.log.XXXXXXXX")
export DOMAINS=$(mktemp "${SCRATCHDIR}/pantheon-domains.domains.XXXXXXXX")

echo "Getting site list..."
terminus org:site:list "${PANTHEON_ORG}" --format json | jq -r '.[] | select(.plan_name != "Sandbox") | .name' > "${SITES}"

function get_domains {
    site="$1"
    terminus domain:list "${site}.live" --format json | \
      jq -r '.[] | .id' | \
      grep -v pantheonsite.io | sed "s/\$/,${site}/" >> "${DOMAINS}"
}

export -f get_domains

echo "Getting domains for each Live site..."
cat "${SITES}" | rust-parallel --shell-path "$(which bash)" --jobs "${PARALLELISM}" --progress-bar --shell "get_domains" > "${LOG}"
cat "${LOG}"

grep -v test.webservices.umich.edu "${DOMAINS}" | sort -u > "${OUTFILE}"
echo "Done. List of domains is in:"
echo "${OUTFILE}"
