#!/usr/bin/env bash
#
# get_upstreams
#
# Gets the PHP versions of all Pantheon sites in a Pantheon org.
#

PANTHEON_ORG="${PANTHEON_ORG:-regents-of-the-university-of-michigan}"
PARALLELISM=8

OUTFILE="pantheon-upstreams-$(date +%Y%m%d).csv"

SHELL="$(which bash)"

if [ -d './tmp' ] ; then
    SCRATCHDIR="$(pwd)/tmp"
else
    SCRATCHDIR="/tmp"
fi

SITES=$(mktemp "${SCRATCHDIR}/pantheon-upstreams.sites.XXXXXXXX")
LOG=$(mktemp "${SCRATCHDIR}/pantheon-upsreams.log.XXXXXXXX")
export WORKDIR=$(mktemp -d "${SCRATCHDIR}/pantheon-upstreams.scratch.XXXXXXXX")


function get_stuff {
  site_name="$1"
  info=$(terminus site:info "${site_name}" --field=upstream 2>/dev/null)
  echo "${site_name},${info}" >> "${WORKDIR}/${site_name}"
}
export -f get_stuff

echo "===== Getting site IDs"

terminus org:site:list "${PANTHEON_ORG}" --fields=name --format=string > "${SITES}"

echo -e "\n\n===== Getting site upstreams"
echo "site,upstream" > "${OUTFILE}"

rust-parallel --input-file "${SITES}" --jobs "${PARALLELISM}" --progress-bar --shell-path "${SHELL}" --shell "get_stuff" > "${LOG}"
cat "${LOG}"
cat "${WORKDIR}"/* >> "${OUTFILE}"

rm -f "${SITES}" "${LOG}"
rm -rf "${WORKDIR}"

echo -e "\n\n===== Done, site upstream list is in:\n${OUTFILE}"

