#!/usr/bin/env bash
#
# get_db_versions
#
# Gets the version of the database for the Live environment of all sites in a Pantheon org.
#

PANTHEON_ORG="${PANTHEON_ORG:-regents-of-the-university-of-michigan}"
PARALLELISM=16

OUTFILE="pantheon-db-versions-$(date +%Y%m%d).csv"

SHELL="$(which bash)"

if [ -d './tmp' ] ; then
    SCRATCHDIR="$(pwd)/tmp"
else
    SCRATCHDIR="/tmp"
fi

SITES=$(mktemp "${SCRATCHDIR}/pantheon-db-versions.sites.XXXXXXXX")
LOG=$(mktemp "${SCRATCHDIR}/pantheon-db-versions.log.XXXXXXXX")
export WORKDIR=$(mktemp -d "${SCRATCHDIR}/pantheon-wp-plugins.scratch.XXXXXXXX")


function get_stuff {
  site_name="$1"
  for environ in "live" ; do
    db_command=$(terminus conn:info "${site_name}.${environ}" --fields=mysql_command --format=string)
    version=$(${db_command} --batch --skip-column-names --execute "SELECT VERSION()" 2>/dev/null)
    echo "${site_name},${environ},${version}" >> "${WORKDIR}/${site_name}"
  done
}
export -f get_stuff

echo "===== Getting site IDs"

terminus org:site:list "${PANTHEON_ORG}" --fields=name --format=string > "${SITES}"

echo -e "\n\n===== Getting DB versions"
echo "site,env,db_version" > "${OUTFILE}"

rust-parallel --input-file "${SITES}" --jobs "${PARALLELISM}" --progress-bar --shell-path "${SHELL}" --shell "get_stuff" > "${LOG}"
cat "${LOG}"
cat "${WORKDIR}"/* >> "${OUTFILE}"

rm -f "${SITES}" "${LOG}"
rm -rf "${WORKDIR}"

echo -e "\n\n===== Done, site DB versions list is in:\n${OUTFILE}"

